config/routes.rb
CONZQ::Application.routes.draw do
  root to: "sessions#root" # BACKBONE

  # --------------------------------------------------
  # BACKBONE

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :update] do
      resources :watchlists, only: [:create, :update, :destroy]
    end

    resources :posts, only: [:create, :show, :update, :destroy] do
      resources :comments, only: [:show]
    end

    resources :tv_shows, only: [:index, :show]
    resource :search, only: [:show]

    get '/front', to: "tv_shows#front_page", as: "front_page"
    get '/search/input_search', to: "searches#text_search", as: "text_search"
    get '/search/categories', to: "searches#categories", as: "categories"
    get '/rest_genres', to: "tv_shows#rest_genres", as: "rest_genres"
  end



  # --------------------------------------------------
  # RAILS

  resources :users
  resource :session
  resource :search, only: [:new]

  # FACEBOOK LOGIN
  get '/auth/facebook/callback', to: 'oauth_callbacks#facebook'
  get '/users/:id/username', to: 'users#update_username', as: 'update_username'

  # SEARCH ROUTES
  # get "/search", to: "searches#show", as: "search_query"
  # post "/search/:search_params/sort", to: "searches#sort", as: "sort"
  get "/input-search", to: "searches#text_search", as: "text_search"

  # TV SHOW ROUTES
  get "/tv/index", to: "tv_shows#index", as: "tv_shows"
  get "/tv/new", to: "tv_shows#new", as: "new_tv"
  post "/tv", to: "tv_shows#create"
  get "/tv/:id", to: "tv_shows#show", as: "tv_show"
  get "/tv/:id/edit", to: "tv_shows#edit", as: "edit_tv"
  put "/tv/:id", to: "tv_shows#update", as: "update_tv"

  resources :posts, only: [:create, :destroy]

  # AUTOCOMPLETE ROUTE
  post "/tv/new/auto", to: "tv_shows#auto_complete_form", as: "auto_complete"

  # WATCHLIST ROUTES
  # post "/tv/:tv_id/watchlist", to: "watchlists#create", as: "tv_watchlist"
  # put "/watchlist/:id", to: "watchlists#update", as: "update_watchlist"

  # FAVORITE ROUTES
  # post "/tv/:tv_id/favorite", to: "favorites#create", as: "add_fav"
  # delete "/tv/:tv_id/favorite", to: "favorites#destroy", as: "delete_fav"

  # UNFOLLOW ROUTE
  # delete "/user/:user_id/unfollow", to: "follows#destroy", as: "unfollow"
end

app/models/watchlist.rb
class Watchlist < ActiveRecord::Base
  STATUSES = ["Currently Watching", "Plan to Watch", "Completed", "Dropped"]
  
  validates :status, presence: true, inclusion: { in: STATUSES }
  
  belongs_to :user
  belongs_to :tv_show
end

app/controllers/api/watchlists_controller.rb
class Api::WatchlistsController < ApplicationController
  def create
    @watchlist = current_user.watchlists.new(watchlist_params)
    
    if @watchlist.save
      render json: @watchlist
    else
      render json: { errors: @watchlist.errors.full_messages }, 
             status: :unprocessable_entity
    end
  end
  
  def update
    @watchlist = Watchlist.find(params[:id])
    
    if @watchlist.update_attributes(watchlist_params)
      render json: @watchlist
    else
      render json: { errors: @watchlist.errors.full_messages }, 
             status: :unprocessable_entity
    end
  end
  
  def destroy
    @watchlist = Watchlist.find(params[:id])
    @watchlist.destroy!
    render json: @watchlist
  end
  
  private
  def watchlist_params
    params.require(:watchlist).permit(:tv_show_id, :status)
  end
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
  before_action :require_signed_in, only: [:create, :update]
  
  def index
    @user = User.find(params[:user_id])
    @watchlist = @user.watchlist_shows
  end
  
  def create
    @tv = TvShow.find(params[:tv_id])
    @watchlist = current_user.watchlists.new(watchlist_params)
    @watchlist.tv_show = @tv
    
    unless @watchlist.save
      flash[:errors] = ["You've already added this series to your watchlist!"]
    end
    
    redirect_to :back
  end
  
  def update
    @watchlist = Watchlist.find(params[:id])
    
    unless @watchlist.update_attributes(watchlist_params)
      flash[:errors] = @watchlist.errors.full_messages
    end
    
    redirect_to :back
  end
  
  private
  def watchlist_params
    params.require(:watchlist).permit(:status)
  end
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/watchlists/_nav.html.erb
<ul class="watchlist-nav group">
  <% Watchlist::STATUSES.each do |status| %>
    <li>
      <a href="#<%= status.split(" ").first %>">
        <% if location == status %>
          <strong><%= status %></strong>
        <% else %>
          <%= status %>
        <% end %>
      </a>
    </li>
  <% end %>
</ul>

app/views/watchlists/_result.html.erb
<a class="group" href="<%= tv_show_url(tv) %>">
	<img src="<%= tv.photo.url(:thumb) %>">
	<%= tv.title %>
  <%= render partial: "status", locals: { tv: tv } %>
</a>

app/views/watchlists/_status.html.erb
<% if !signed_in? || !current_user.watchlist_shows.exists?(tv.id) %>
  <ul class="watch_dropdown">
    <li><strong>Add to Watchlist</strong></li>
    
    <% ["Currently Watching", "Plan to Watch"].each do |status| %>
      <li>
        <form action="<%= tv_watchlist_url(tv) %>" method="post">
          <%= form_auth %>
          <input type="hidden" 
                 name="watchlist[status]" 
                 value="<%= status %>">
               
          <button><%= status %></button>
        </form>
      </li>
    <% end %>
  </ul>
<% else %>
  <% watchlist = current_user.watchlists.find_by(tv_show_id: tv.id) %>
  
  <form action="<%= update_watchlist_url(watchlist) %>" method="post">
    <%= form_auth %>
    <input type="hidden" name="_method" value="put">
    
    <select name="watchlist[status]">
      <% Watchlist::STATUSES.each do |status| %>
        <option value="<%= status %>" <%= 'selected' if watchlist.status == status %>><%= status %></option>
      <% end %>
    </select>
    
    <button>Change status</button>
  </form>
  
  <br>
<% end %>

app/views/watchlists/index.html.erb
<h1><%= @user.username %>'s Watchlist</h1>

<%= render partial: "users/profilenav", locals: { location: "Watchlist" } %>

<section class="profile">

<% Watchlist::STATUSES.each do |status| %>

  <h2 id="<%= status.split(" ").first %>"><%= status %></h2>
  <%= render partial: "nav", locals: { location: status } %>

  <ul class="show-list">
    <% @watchlist.where(watchlists: { status: status }).each do |show| %>
      <li><%= render partial: "result", locals: { tv: show } %></li>
    <% end %>
  </ul>

<% end %>


</section>