config/routes.rb
CONZQ::Application.routes.draw do
  root to: "sessions#root" # BACKBONE

  # --------------------------------------------------
  # BACKBONE

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :update] do
      resources :watchlists, only: [:create, :update, :destroy]
    end

    resources :posts, only: [:create, :show, :update, :destroy] do
      resources :comments, only: [:show]
    end

    resources :tv_shows, only: [:index, :show]
    resource :search, only: [:show]

    get '/front', to: "tv_shows#front_page", as: "front_page"
    get '/search/input_search', to: "searches#text_search", as: "text_search"
    get '/search/categories', to: "searches#categories", as: "categories"
    get '/rest_genres', to: "tv_shows#rest_genres", as: "rest_genres"
  end



  # --------------------------------------------------
  # RAILS

  resources :users
  resource :session
  resource :search, only: [:new]

  # FACEBOOK LOGIN
  get '/auth/facebook/callback', to: 'oauth_callbacks#facebook'
  get '/users/:id/username', to: 'users#update_username', as: 'update_username'

  # SEARCH ROUTES
  # get "/search", to: "searches#show", as: "search_query"
  # post "/search/:search_params/sort", to: "searches#sort", as: "sort"
  get "/input-search", to: "searches#text_search", as: "text_search"

  # TV SHOW ROUTES
  get "/tv/index", to: "tv_shows#index", as: "tv_shows"
  get "/tv/new", to: "tv_shows#new", as: "new_tv"
  post "/tv", to: "tv_shows#create"
  get "/tv/:id", to: "tv_shows#show", as: "tv_show"
  get "/tv/:id/edit", to: "tv_shows#edit", as: "edit_tv"
  put "/tv/:id", to: "tv_shows#update", as: "update_tv"

  resources :posts, only: [:create, :destroy]

  # AUTOCOMPLETE ROUTE
  post "/tv/new/auto", to: "tv_shows#auto_complete_form", as: "auto_complete"

  # WATCHLIST ROUTES
  # post "/tv/:tv_id/watchlist", to: "watchlists#create", as: "tv_watchlist"
  # put "/watchlist/:id", to: "watchlists#update", as: "update_watchlist"

  # FAVORITE ROUTES
  # post "/tv/:tv_id/favorite", to: "favorites#create", as: "add_fav"
  # delete "/tv/:tv_id/favorite", to: "favorites#destroy", as: "delete_fav"

  # UNFOLLOW ROUTE
  # delete "/user/:user_id/unfollow", to: "follows#destroy", as: "unfollow"
end

app/models/tv_show.rb
# encoding: utf-8
require 'addressable/uri'

class TvShow < ActiveRecord::Base
  enum status: ["Currently Airing", "Current", "Ended", "Cancelled"]
  STATUSES = ["Currently Airing", "Current", "Ended", "Cancelled"]

  validates :title, presence: true
  validates :imdb_id, uniqueness: true

  has_attached_file :photo, styles: {
      big: "400x400>",
      medium: "160x200#",
      thumb: "50x50#"
    }, default_url: "/images/missing_:style.jpg"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  has_many :tv_genres, dependent: :destroy
  has_many :genres, through: :tv_genres

  has_many :tv_decades, dependent: :destroy
  has_many :decades, through: :tv_decades

  has_many :watchlists, dependent: :destroy
  has_many :watchers, through: :watchlists, source: :user

  has_many :favorites, dependent: :destroy
  has_many :lovers, through: :favorites, source: :user

  has_many :posts, inverse_of: :tv_show, dependent: :destroy

  belongs_to :admin,
    class_name: "User",
    foreign_key: :admin_id,
    inverse_of: :tv_shows

  include PgSearch
  multisearchable against: [:title]

  def genre_names
    @genres ||= self.genres.pluck(:name)
  end

  def decade_years
    @decades ||= self.decades.pluck(:years)
  end

  def apply_imdb_rating
    omdb_info = parse_omdb
    self.rating = omdb_info["imdbRating"]
    self.imdb_id = omdb_info["imdbID"]
  end

  def auto_complete
    omdb_info = parse_omdb
    tmdb_info = parse_tmdb

    if omdb_info
      self.blurb = omdb_info["Plot"]

      years = omdb_info["Year"].split("–")
      self.year_start = years.first

      if years.count > 1
        self.year_end = years.last
      else
        self.status = "Currently Airing"
      end

      @genres = omdb_info["Genre"].split(",")
    end

    if tmdb_info
      self.seasons = tmdb_info["number_of_seasons"]
      self.network = tmdb_info["networks"].map { |hash| hash["name"] }.join("/")
    end

    nil
  end

  def assign_decade
    start_yr = self.year_start
    return unless start_yr
    end_yr = self.year_end.nil? ? Time.now.year : self.year_end

    parsed_start = Decade.parse(start_yr)
    parsed_end = Decade.parse(end_yr)
    decades = [parsed_start, parsed_end]

    if (end_yr - start_yr > 10) && (parsed_start != parsed_end)
      year_jump = start_yr + 10

      until year_jump >= end_yr
        decades << Decade.parse(year_jump)
        year_jump += 10
      end
    end

    decade_ids = decades.uniq.map do |years|
      Decade.find_by(years: years).id if Decade.find_by(years: years)
    end

    self.decade_ids = decade_ids
  end

  private
  def parse_omdb
    show = Addressable::URI.new(
          scheme: "http",
          host: "www.omdbapi.com",
          path: "",
          query_values: {
            t: self.title
          }).to_s

    JSON.parse(RestClient.get(show))
  end

  def parse_tmdb
    tmdb_external_search = Addressable::URI.new(
          scheme: "http",
          host: "api.themoviedb.org",
          path: "3/find/" + parse_omdb["imdbID"],
          query_values: {
            api_key: ENV["TMDB_KEY"],
            external_source: "imdb_id"
          }).to_s

    parsed_tmdb = JSON.parse(RestClient.get(tmdb_external_search))

    unless parsed_tmdb["tv_results"].empty?
      tmdb_show_id = parsed_tmdb["tv_results"].first["id"].to_s

      tmdb_show_info = Addressable::URI.new(
            scheme: "http",
            host: "api.themoviedb.org",
            path: "3/tv/" + tmdb_show_id,
            query_values: {
              api_key: ENV["TMDB_KEY"]
            }).to_s

      JSON.parse(RestClient.get(tmdb_show_info))
    else
      nil
    end
  end
end

app/controllers/api/tv_shows_controller.rb
class Api::TvShowsController < ApplicationController
  def index
    @tvs = TvShow.all
 
    render 'api/tv/index'
  end
  
  def show
    tv = TvShow.find(params[:id])
    
    render partial: 'api/tv/tv_show', locals: { tv_show: tv }
  end
  
  def front_page
    @tvs = TvShow.where(status: "Currently Airing")
    
    render 'api/tv/front'
  end
  
  def rest_genres
    @genres = Genre.where(top_level: false).order(:name)
    
    render "api/tv/genres"
  end
  
  private
  def tv_params
    params.require(:tv).permit(:title, :photo, :seasons, :year_start,
                               :year_end, :status, :blurb, :network)
  end

  def check_admin
    unless signed_in? && current_user.admin
      render json: "You are not allowed to perform this action!"
    end
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :check_admin, only: [
    :index, :new, :create, :edit, :update, :destroy
  ]

  def index
    @tvs = current_user.tv_shows.order(:title)
  end

  def new
    @tv = TvShow.new
    @genres = Genre.where(top_level: false).order(:name)
  end

  def create
    @tv = TvShow.new(tv_params)
    @tv.admin = current_user
    @tv.genre_ids = params[:genre_ids]
    @tv.apply_imdb_rating
    @tv.assign_decade

    if @tv.save
      redirect_to @tv
    else
      flash.now[:errors] = @tv.errors.full_messages
      render :new
    end
  end

  def show
    @tv = TvShow.includes(:posts).find(params[:id])
    @posts = @tv.posts.order("created_at DESC")
  end

  def edit
    @tv = TvShow.find(params[:id])
    @genres = Genre.where(top_level: false).order(:name)
  end

  def update
    @tv = TvShow.find(params[:id])
    @tv.genre_ids = params[:genre_ids]

    if @tv.update_attributes(tv_params)
      redirect_to @tv
    else
      flash.now[:errors] = @tv.errors.full_messages
      render :edit
    end
  end

  def auto_complete_form
    @tv = TvShow.new(title: params[:tv][:title])
    @tv.auto_complete

    @genres = Genre.all.order(:name)
    render :new
  end

  private
  def tv_params
    params.require(:tv).permit(:title, :photo, :seasons, :year_start,
                               :year_end, :status, :blurb, :network)
  end

  def post_params
    params.require(:post).permit(:body)
  end

  def check_admin
    unless signed_in? && current_user.admin
      flash[:errors] = ["You are not allowed to perform that action!"]
      redirect_to root_url
    end
  end
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/tv_shows/_form.html.erb
<%= render partial: "layouts/error" %>

<form class="tv-form" action="<%= action_url %>" 
			method="post" enctype="multipart/form-data">
  <%= form_auth %>

  <% if put %>
  <input type="hidden" name="_method" value="put">
  <% end %>

  <label for="tv_title">Title:</label>
  <input id="tv_title" type="text" name="tv[title]" value="<%= @tv.title %>">

  <label for="tv_photo">Photo:</label>
	<% unless @tv.photo.url =~ /missing/ %>
	<img src="<%= @tv.photo.url(:medium) %>">
	<% end %>
  <input id="tv_photo" type="file" name="tv[photo]">

  <label>Genre(s):</label>
  <div class="genre-form" data-id="<%= @tv.id %>"></div>

  <label for="tv_network">Network: (please abbreviate)</label>
  <input id="tv_network" type="text" 
				 name="tv[network]" value="<%= @tv.network %>">

  <label for="tv_seasons"># of seasons:</label>
  <input id="tv_seasons" type="text" 
				 name="tv[seasons]" value="<%= @tv.seasons %>">

  <label for="tv_year_start">Year Start:</label>
  <input id="tv_year_start" type="text" 
				 name="tv[year_start]" value="<%= @tv.year_start %>">

  <label for="tv_year_end">Year End: (leave blank if currently airing)</label>
  <input id="tv_year_end" type="text" 
				 name="tv[year_end]" value="<%= @tv.year_end %>">

  <label for="tv_status">Status:</label>
  <select id="tv_status" name="tv[status]">
    <option value=""></option>

    <% TvShow::STATUSES.each do |status| %>
    <option value="<%= status %>" <%= 'selected' if @tv.status == status %>>
    	<%= status %>
		</option>
    <% end %>
  </select>

  <label for="tv_blurb">Summary:</label>
  <textarea id="tv_blurb" name="tv[blurb]"><%= @tv.blurb %></textarea>

  <center><button><%= button_text %></button></center>
</form>

app/views/tv_shows/_tv_show.html.erb
<a href="/tv/<%= tv_show.id %>">
	<img src="<%= tv_show.photo.url(:medium) %>">
	
	<strong><%= tv_show.title %></strong>
</a>

app/views/tv_shows/edit.html.erb
<h1>
	Edit <em><%= @tv.title %></em>'s info
</h1>

<%= render partial: "form", locals: {
  action_url: update_tv_url(@tv),
  put: true,
  button_text: "Update"
} %>

app/views/tv_shows/index.html.erb
<h1>My Series</h1>

<ul class="admin-index group">
  <% @tvs.each do |show| %>
    <li><%= render show %></li>
  <% end %>
</ul>

app/views/tv_shows/new.html.erb
<h1>Add a series</h1>

<section class="new-tv-form-container">
	<%= render partial: "layouts/error" %>
	
	<h2>Auto Complete with IMDB</h2>

	<form class="auto-complete" action="<%= auto_complete_url %>" method="post">
	  <%= form_auth %>

	  <label for="tv_title">Title:</label>
	  <input id="tv_title" type="text" name="tv[title]">

	  <button>Fill out form</button>
	</form>

	<p class="or">or</p>

	<h2>Add manually</h2>

	<%= render partial: "form", locals: {
	  action_url: tv_url,
	  button_text: "Add Series",
	  put: false
	  } %>
</section>

app/views/tv_shows/original_tv_show.html.erb
<div class="tv-show-page-container">
	<h1>
		<%= @tv.title %>
	
		<% if current_user == @tv.admin %>
		<a class="edit-profile tv" href="<%= edit_tv_url(@tv) %>">Edit Info</a>
		<% end %>
	</h1>

	<div id="tv-show-page-statuses" data-id="<%= @tv.id %>"></div>

	<img src="<%= @tv.photo.url(:big) %>">
	
	<section class="tv-info-container group">
		<ul class="tv-info-left">
		  <li>
		    <strong>Genre(s):</strong>
		    <%= @tv.genre_names.join(", ") %>
		  </li>

		  <li>
		    <strong>IMDB rating:</strong>
		    <%= @tv.rating %>
		  </li>

		  <li>
		    <strong>Network:</strong>
		    <%= @tv.network %>
		  </li>

		  <li>
		    <%= @tv.seasons %> seasons, <%= @tv.year_start %> -
		    <%= @tv.year_end.nil? ? "present" : @tv.year_end %>
		  </li>

		  <li>
		    <strong>Status:</strong>
		    <%= @tv.status %>
			</li>
		</ul>

	  <div class="tv-info-right">
	    <p><%= @tv.blurb %></p>
		</div>
	</section>
</div>








<!-- TV SHOW CSS -->

// SHOW PAGE
.tv-show-page-container {
  width: 650px;
  margin: auto;
  margin-bottom: 20px;
}

.edit-profile.tv {
	position: relative;
	bottom: 8px;
	display: inline-block;
}

.tv-show-page-container > img {
	margin: auto;
}

.tv-info-container {
	position: relative;
	margin-top: 30px;
}

.tv-info-left {
	float: left;
	width: 190px;
	padding: 10px;
	border: 1px solid #ccc;
}

.tv-info-left > li {
  padding: 10px 0;
}

.tv-info-left strong {
	font-weight: 700;
}

.tv-info-right {
	position: absolute;
	right: 0;
	width: 420px;
	height: 100%;
  font-size: 20px;
}

.tv-info-right > p {
	padding: 20px 40px;
	font-style: italic;
	line-height: 1.2;
	background: #D2EDFA;
}

app/views/tv_shows/show.html.erb
<div class="tv-show-page-container">
  <h1>
    <%= @tv.title %>

    <% if current_user == @tv.admin %>
    <a class="edit-profile tv" href="<%= edit_tv_url(@tv) %>">Edit Info</a>
    <% end %>
  </h1>

  <div id="tv-show-page-statuses" data-id="<%= @tv.id %>"></div>

  <img src="<%= @tv.photo.url(:big) %>">

  <section class="tv-info-container group">
    <ul class="tv-info-left">
      <li>
        <strong>Genre(s):</strong>
        <%= @tv.genre_names.join(", ") %>
      </li>

      <li>
        <strong>IMDB rating:</strong>
        <%= @tv.rating %>
      </li>

      <li>
        <strong>Network:</strong>
        <%= @tv.network %>
      </li>

      <li>
        <%= @tv.seasons %> seasons, <%= @tv.year_start %> -
        <%= @tv.year_end.nil? ? "present" : @tv.year_end %>
      </li>

      <li>
        <strong>Status:</strong>
        <%= @tv.status %>
      </li>
    </ul>

    <div class="tv-info-right">
      <p><%= @tv.blurb %></p>
    </div>
  </section>
</div>

<div class="tv-posts-container">
  <strong class="title">Recent posts</strong>

  <form id="tv-post" action="<%= posts_url(tv_show_id: @tv.id) %>" method="post">
    <%= form_auth %>

    <textarea name="post[body]"></textarea>
  </form>

  <script>
  $(document).ready(function () {
    $("#tv-post").on("keydown", function () {
      if (event.which === 38) {
        $(this).submit();
      }
    });
  });
  </script>

  <ul class="tv-posts">
    <% if @posts.empty? %>
    <li>No posts.</li>
    <% else %>

    <% @posts.each do |post| %>
    <li>
      <p><%= post.body %></p>

      <strong class="username">
        <a href="/#/users/<%= post.user.id %>"><%= post.user.username %></a>
      </strong>

      <strong class="time">
        <%= distance_of_time_in_words(post.created_at, Time.zone.now) %> ago
      </strong>
    </li>
    <% end %>

    <% end %>
  </ul>
</div>