config/routes.rb
CONZQ::Application.routes.draw do
  root to: "sessions#root" # BACKBONE

  # --------------------------------------------------
  # BACKBONE

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :update] do
      resources :watchlists, only: [:create, :update, :destroy]
    end

    resources :posts, only: [:create, :show, :update, :destroy] do
      resources :comments, only: [:show]
    end

    resources :tv_shows, only: [:index, :show]
    resource :search, only: [:show]

    get '/front', to: "tv_shows#front_page", as: "front_page"
    get '/search/input_search', to: "searches#text_search", as: "text_search"
    get '/search/categories', to: "searches#categories", as: "categories"
    get '/rest_genres', to: "tv_shows#rest_genres", as: "rest_genres"
  end



  # --------------------------------------------------
  # RAILS

  resources :users
  resource :session
  resource :search, only: [:new]

  # FACEBOOK LOGIN
  get '/auth/facebook/callback', to: 'oauth_callbacks#facebook'
  get '/users/:id/username', to: 'users#update_username', as: 'update_username'

  # SEARCH ROUTES
  # get "/search", to: "searches#show", as: "search_query"
  # post "/search/:search_params/sort", to: "searches#sort", as: "sort"
  get "/input-search", to: "searches#text_search", as: "text_search"

  # TV SHOW ROUTES
  get "/tv/index", to: "tv_shows#index", as: "tv_shows"
  get "/tv/new", to: "tv_shows#new", as: "new_tv"
  post "/tv", to: "tv_shows#create"
  get "/tv/:id", to: "tv_shows#show", as: "tv_show"
  get "/tv/:id/edit", to: "tv_shows#edit", as: "edit_tv"
  put "/tv/:id", to: "tv_shows#update", as: "update_tv"

  resources :posts, only: [:create, :destroy]

  # AUTOCOMPLETE ROUTE
  post "/tv/new/auto", to: "tv_shows#auto_complete_form", as: "auto_complete"

  # WATCHLIST ROUTES
  # post "/tv/:tv_id/watchlist", to: "watchlists#create", as: "tv_watchlist"
  # put "/watchlist/:id", to: "watchlists#update", as: "update_watchlist"

  # FAVORITE ROUTES
  # post "/tv/:tv_id/favorite", to: "favorites#create", as: "add_fav"
  # delete "/tv/:tv_id/favorite", to: "favorites#destroy", as: "delete_fav"

  # UNFOLLOW ROUTE
  # delete "/user/:user_id/unfollow", to: "follows#destroy", as: "unfollow"
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  has_attached_file :photo, styles: {
      big: "360x360>",
      medium: "160x200#",
      thumb: "50x50#"
    }, default_url: "/images/missing_:style.jpg"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  has_many :watchlists, dependent: :destroy
  has_many :watchlist_shows, through: :watchlists, source: :tv_show

  has_many :favorites, dependent: :destroy
  has_many :favorite_shows, through: :favorites, source: :tv_show

  # PEOPLE THEY FOLLOW
  has_many :follows, foreign_key: :follower_id, dependent: :destroy
  has_many :idols, through: :follows, inverse_of: :followers

  # PEOPLE WHO FOLLOW THEM
  has_many :followings, 
    class_name: "Follow", 
    foreign_key: :idol_id, 
    dependent: :destroy
  has_many :followers, through: :followings, inverse_of: :idols
  
  has_many :posts, inverse_of: :user, dependent: :destroy
  
  has_many :comments, 
    foreign_key: :commenter_id, 
    inverse_of: :commenter, 
    dependent: :destroy
  
  has_many :tv_shows,
    foreign_key: :admin_id,
    inverse_of: :admin
    
  before_destroy :release_admin
  
  include PgSearch
  multisearchable against: [:username, :email]
  
  def currently_watching_shows
    TvShow.joins(:watchlists).where(
      "watchlists.user_id = #{self.id} AND 
      watchlists.status = 'Currently Watching'"
    )
  end
  
  def plan_to_watch_shows
    TvShow.joins(:watchlists).where(
      "watchlists.user_id = #{self.id} AND 
      watchlists.status = 'Plan to Watch'"
    )
  end
  
  def completed_shows
    TvShow.joins(:watchlists).where(
      "watchlists.user_id = #{self.id} AND 
      watchlists.status = 'Completed'"
    )
  end
  
  def dropped_shows
    TvShow.joins(:watchlists).where(
      "watchlists.user_id = #{self.id} AND 
      watchlists.status = 'Dropped'"
    )
  end
  
  def watchlist_statuses
    if @watchlist_hash.nil?
      @watchlist_hash = {}
      
      self.watchlists.each do |watch|
        @watchlist_hash[watch.tv_show_id] = watch.status 
      end
    end
    
    @watchlist_hash
  end

  def password
    @password
  end

  def password=(pass)
    @password = pass
    self.password_digest = BCrypt::Password.create(pass)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, pass)
    user = User.find_by(username: username)
    return unless user

    user.is_password?(pass) ? user : nil
  end

  def is_password?(pass)
    BCrypt::Password.new(self.password_digest).is_password?(pass)
  end
  
  private
  def release_admin
    self.tv_shows.each do |show|
      show.admin_id = nil
      show.save!
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    
    render partial: "api/users/user", locals: { user: @user }
  end
  
  def update
    @user = User.find(params[:id])
    
    if params[:favorite]
      tv_show_id = params[:favorite][:tv_show_id]
      favorite = @user.favorites.find_by(tv_show_id: tv_show_id)
      
      if !favorite.try(:destroy!)
        favorite = @user.favorites.new(tv_show_id: tv_show_id)
        favorite.save!
      end
      
      render json: @user
      
    elsif params[:idol_id]
      follow = current_user.follows.find_by(idol_id: params[:idol_id])
      
      if !follow.try(:destroy!)
        follow = current_user.follows.new(idol_id: params[:idol_id])
        follow.save!
      end
      
      render json: @user
      
    else
      @user.update_attributes(user_params)
      
      render partial: "api/users/user", locals: { user: @user } 
    end      
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :photo, :bio)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, only: [:update_username, :edit, :update]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to edit_user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def update_username
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      if params[:update]
        redirect_to edit_user_url(@user)
      else
        redirect_to '/#/users/' + @user.id.to_s
      end
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to :back
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :photo, :bio)
  end
  
  def check_user
    if current_user != User.find(params[:id])
      flash[:errors] = ["You are not allowed to perform that action!"]
      redirect_to root_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<section class="user-fun-facts">
  <div class="input-group">
		<label for="user_bio">
			Give us a little something to share on your profile! ☺
		</label>
		<textarea id="user_bio" name="user[bio]"></textarea>
	</div>

  <div class="input-group">
		<label for="user_photo">Profile Picture:</label>
		<input id="user_photo" type="file" name="user[photo]">
	</div>
</section>

app/views/users/_profilenav.html.erb
<div class="header-links-container group">
<ul class="header-links">
  <li class=<%= 'location' if location == "Watchlist" %>><a href="<%= user_watchlists_url(@user) %>">Watchlist</a></li>
  <li class=<%= 'location' if location == "Favorites" %>><a href="<%= user_favorites_url(@user) %>">Favorites</a></li>
  <li class=<%= 'location' if location == "Followers" %>><a href="<%= user_follows_url(@user) %>">Followers & Followees</a></li>
</ul>
</div>

<%= render partial: "follows/status", locals: { user: @user } %>

app/views/users/_user.html.erb
<a href="/#/users/<%= user.id %>">
	<img src="<%= user.photo.url(:thumb) %>">
</a>

<ul class="user-info">
	<li class="username">
		<a href="/#/users/<%= user.id %>"><%= user.username %></a>
	</li>
	
	<li>
		<a href="/#/users/<%= user.id %>">
			currently watching
			<strong><%= user.currently_watching_shows.count %></strong> shows
		</a>
	</li>
	
	<li>
		<a href="/#/users/<%= user.id %>">
			<span class="heart"></span>
			<p><%= user.favorites.count %> favorite shows</p>
		</a>
	</li>
</ul>

app/views/users/edit.html.erb
<h1>Your Profile</h1>

<form class="user-form" action="<%= user_url(@user) %>" method="post" 
	enctype="multipart/form-data">
	<%= form_auth %>
	<input type="hidden" name="_method" value="put">
	
  <div class="input-group">
		<label for="user_bio">
			Give us a little something to share on your profile! ☺
		</label>
		<textarea id="user_bio" name="user[bio]"></textarea>
	</div>

  <div class="input-group">
		<label for="user_photo">Profile Picture:</label>
		<input id="user_photo" type="file" name="user[photo]">
	</div>
	
	<center>
		<button>Submit</button>
		<a href="/#/users/<%= @user.id %>">Skip</a>
	</center>
</form>

app/views/users/new.html.erb
<h1>Register</h1>

<section class="sign-in">

<form class="user-form" action="<%= users_url %>" method="post">
  <%= form_auth %>
	
  <div class="input-group">
	  <label for="user_email">Email:</label>
	  <input id="user_email" type="text" 
					 name="user[email]" value="<%= @user.email %>">
	</div>
	
	<div class="input-group">
		<label for="user_username">Username:</label>
	  <input id="user_username" type="text" 
					 name="user[username]" value="<%= @user.username %>">
	</div>
	
  <div class="input-group">
		<label for="user_password">Password:</label>
	  <input id="user_password" type="password" name="user[password]">
	</div>

  <center><button>Sign Up!</button></center>
</form>

</section>

<p class="or">or</p>

<button class="fb-login">
	<img src="/images/fb_white_logo.png">
	<p>Login with Facebook</p>
</button>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

app/views/users/update_username.html.erb
<h1>Your Profile</h1>

<form class="user-form" action="<%= user_url(@user) %>" method="post">
	<%= form_auth %>
	<input type="hidden" name="_method" value="put">
	<input type="hidden" name="update" value="username">
	
  <div class="input-group">
		<label for="user_username">
			Choose a unique username to represent yourself:
		</label>
		<input id="user_username" type="text" 
					 name="user[username]" value="<%= @user.username %>">
	</div>
	
	<center>
		<button>Next &raquo;</button>
	</center>
</form>