config/routes.rb
CONZQ::Application.routes.draw do
  root to: "sessions#root" # BACKBONE

  # --------------------------------------------------
  # BACKBONE

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :update] do
      resources :watchlists, only: [:create, :update, :destroy]
    end

    resources :posts, only: [:create, :show, :update, :destroy] do
      resources :comments, only: [:show]
    end

    resources :tv_shows, only: [:index, :show]
    resource :search, only: [:show]

    get '/front', to: "tv_shows#front_page", as: "front_page"
    get '/search/input_search', to: "searches#text_search", as: "text_search"
    get '/search/categories', to: "searches#categories", as: "categories"
    get '/rest_genres', to: "tv_shows#rest_genres", as: "rest_genres"
  end



  # --------------------------------------------------
  # RAILS

  resources :users
  resource :session
  resource :search, only: [:new]

  # FACEBOOK LOGIN
  get '/auth/facebook/callback', to: 'oauth_callbacks#facebook'
  get '/users/:id/username', to: 'users#update_username', as: 'update_username'

  # SEARCH ROUTES
  # get "/search", to: "searches#show", as: "search_query"
  # post "/search/:search_params/sort", to: "searches#sort", as: "sort"
  get "/input-search", to: "searches#text_search", as: "text_search"

  # TV SHOW ROUTES
  get "/tv/index", to: "tv_shows#index", as: "tv_shows"
  get "/tv/new", to: "tv_shows#new", as: "new_tv"
  post "/tv", to: "tv_shows#create"
  get "/tv/:id", to: "tv_shows#show", as: "tv_show"
  get "/tv/:id/edit", to: "tv_shows#edit", as: "edit_tv"
  put "/tv/:id", to: "tv_shows#update", as: "update_tv"

  resources :posts, only: [:create, :destroy]

  # AUTOCOMPLETE ROUTE
  post "/tv/new/auto", to: "tv_shows#auto_complete_form", as: "auto_complete"

  # WATCHLIST ROUTES
  # post "/tv/:tv_id/watchlist", to: "watchlists#create", as: "tv_watchlist"
  # put "/watchlist/:id", to: "watchlists#update", as: "update_watchlist"

  # FAVORITE ROUTES
  # post "/tv/:tv_id/favorite", to: "favorites#create", as: "add_fav"
  # delete "/tv/:tv_id/favorite", to: "favorites#destroy", as: "delete_fav"

  # UNFOLLOW ROUTE
  # delete "/user/:user_id/unfollow", to: "follows#destroy", as: "unfollow"
end

app/views/layouts/_nav.html.erb
<header class="group">
  <nav>
    <a class="logo" href="#/index">Clickster</a>

    <form id="input-search-form" action="<%= text_search_url %>" method="get">
      <input id="text-search"
             type="text"
             name="query"
             value="<%= params[:query] %>"
             placeholder="Search for TV show titles or users">
    </form>

    <ul>
      <li><a id="discover" href="#">Discover</a></li>

      <% if signed_in? %>
      <li class="signed-in">
        <a href="#/users/<%= current_user.id %>">
          <%= current_user.username %>
          <strong class="triangle">▼</strong>
        </a>

        <ul class="profile-dropdown">
          <% if current_user.admin %>
          <li>
            <a href="<%= tv_shows_url %>">My Series</a>
          </li>

          <li>
            <a href="<%= new_tv_url %>">Add a Series</a>
          </li>
          <% end %>

          <li>
            <a href="#/users/<%= current_user.id %>">My Profile</a>
          </li>

          <li>
            <a href="#">Settings</a>
          </li>

          <li>
            <form class="logout-form" action="<%= session_url %>" method="post">
              <%= form_auth %>
              <input type="hidden" name="_method" value="delete">
              <button>Logout</button>
            </form>
          </li>
        </ul>
      </li>
      <% else %>

      <li><a href="<%= new_session_url %>">Sign In</a></li>
      <li><a href="<%= new_user_url %>">Create an account</a></li>

      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clickster</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto:300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", "font-awesome/css/font-awesome", media: "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "layouts/nav" %>

<main class="container">
  <!-- SIDEBAR -->

  <section class="content">
    <%= render partial: "shared/error" %>

    <%= yield %>
  </section>
</main>

<% if current_user %>
<script>
  window.currentUser = { id: <%= current_user.id %> };
</script>
<% end %>


<script>
$(document).ready(function(){
  var $container = $("main.container");
  var $sidebar = $("<section>").addClass("sidebar");
  var $main = $("section.content");

  // BACKBONE
  CONZQ.initialize($container, $sidebar, $main);

  // EXTRA
  $("abbr.timeago").timeago();

  $("input#text-search").on("focus", function () {
    $(this).val("");
  });

  $("a#discover").on("click", function () {
    event.preventDefault();
    $container.toggleClass("open");
  });

});
</script>
</body>
</html>